# Folder settings
fdirCode: C:\Jialiang\Code
fdirData: C:\Jialiang\Data\Ephys
fdirDataCloud: S:\RawData\Ephys
fdirDataRemoteRaw: O:\Ephys
fdirDataRemoteLog: O:\Ephys\Log
fdirDataRemoteMinos: U:\Unity\Minos
fdirKilosort3: C:\Jialiang\Code\Packages\Kilosort3
fdirConda: C:\Users\Jialiang\miniconda3
envKilosort4: ks

# Channel configuration
channelConfig:
  v7:
    aux:
      - Acc1
      - Acc2
      - Acc3
    adc:
      - EyeXLeft
      - EyeYLeft
      - EyePLeft
      - EyeXRight
      - EyeYRight
      - EyePRight
      - JoystickX
      - JoystickY
    dig:
      - Sync
      - Juice
      - None
      - Record
      - Photodiode
      - None
      - None
      - None

# Brain region name mappings
brainRegionMap:
  CA1: HPC
  CA3: HPC
  ML: ITC
  AM: ITC
  F5: vPMC
